### ISSUE TITLE
Errors in samples/core  and samples/ios and environment/ios

### ISSUE THREAD

**Issue by blockaystudio** [siondream/libgdx-cookbook#1]
I'll start off with the first error in core because I just want to be able to run my project and finish this book.........
The type AnimatedSpriteSample.RegionComparator must implement the inherited abstract method Comparator<TextureAtlas.AtlasRegion>.reversed() AnimatedSpriteSample.java /samples-core/src/com/cookbook/samples line 135

**Comment by dsaltares** [comment]
Did you change the Libgdx version in the Gradle files? The build files that come with the project use a compatible Libgdx version, so there are definitely no compilation errors.

**Comment by blockaystudio** [comment]
I figured out my problems, but I did have to change org.robovm.cocoatouch to org.robovm.apple in IOSLAUNCHER in order to make everything work.

**Comment by dsaltares** [comment]
Thanks for the heads up, this has now been fixed (it happened when updating robovm).
