### ISSUE TITLE
are the assets free to use

### ISSUE THREAD

**Issue by tzvetkovg** [siondream/libgdx-cookbook#11]
I would like to know whether the assets in the android project used for the book samples are open source and could be used in other games? Thank you

**Comment by dsaltares** [comment]
As stated in the [LICENSE.md](https://github.com/saltares/libgdx-cookbook/blob/master/LICENSE.md) file, the assets are under Creative Commons BY-NC-SA, which means you are free to use them as long as you give credit to the original creators, you used them on non commercial projects and you distribute them under the same license.
