### ISSUE TITLE
Gradle build unable to find 'aurelienribon/tweenengine.gwt.xml'

### ISSUE THREAD

**Issue by nicofr69** [siondream/libgdx-cookbook#13]
Hello,

I have downloaded the latest version to date (commit cd2edfeb5b5111d023dc4af0c7f54894c3675890 *fixes #10 SwingCanvasSample).

1I build the application with Gradle using `.\gradlew clean build` and get error message

```
:android:preBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:preBuild'.
> failed to find Build Tools revision 19.0.3
```

2) I change in file `samples\android\build.gradle` the `buildToolsVersion "19.0.3"` into `buildToolsVersion "19.1.0"`. This corrects (1).
3) I build the application with Gradle using `.\gradlew clean build` and get the message (extract):

```
:gwt:compileGwt
Loading inherited module 'com.cookbook.samples.GdxDefinitionSuperdev'
   Loading inherited module 'aurelienribon.tweenengine'
      [ERROR] Unable to find 'aurelienribon/tweenengine.gwt.xml' on your classpath; could be a typo, 
       or maybe you forgot to include a classpath entry for source?
```

 Any idea?

Best regards,
Nikolas

**Comment by dsaltares** [comment]
The GWT build and other issues have been fixed here: https://github.com/saltares/libgdx-cookbook/commit/72edd152efb84379a3c4d012a8513262918f13be

**Comment by dsaltares** [comment]
> `:gwt:compileGwt`

You should run `:gwt:gwtSuperDev` or `:gwt:gwtDev` though.
