### ISSUE TITLE
SoundEffectSample

### ISSUE THREAD

**Issue by deimos411** [siondream/libgdx-cookbook#15]
Hello,

There is a little bug in this file SoundEffectSample, on touchDown() function.

this :
Sound sound = sounds.get(MathUtils.random(sounds.size - 1));

return null, as Keys.NUM_1 used on create() method  add a sound starting from 8 ( Keys.NUM_1 ) to 14 ( Keys.NUM_7).

Maybe this line will correct it : 

Sound sound = sounds.get(MathUtils.random(sounds.size - 1) + Keys.NUM_1);

Sincerfully,

**Comment by dsaltares** [comment]
Thanks for reporting the issue!
