### ISSUE TITLE
Update to latest Android gradle build tools

### ISSUE THREAD

**Issue by mars3142** [siondream/libgdx-cookbook#2]
I can't open it with IntelliJ IDEA, because of outdated gradle build tools.

**Comment by dsaltares** [comment]
This weekend I'm going to update the code to use the latest Libgdx version and will fix the compatibility issues.

I suspect it's just a matter of: https://github.com/siondream/ashley-superjumper/commit/ef2d0cec1ca940ff268690f53f2896052ab68d87

Most likely we will have been affected by the API changes, which I will also address.

Sorry for the late reply.

**Comment by dsaltares** [comment]
This has now been fixed 380ee2ea90481f2b80b62df2dccd312db0af7964
