### ISSUE TITLE
TiledMap loader doesn't exist!?

### ISSUE THREAD

**Issue by mars3142** [siondream/libgdx-cookbook#3]
In your book you wrote, that the map can be loaded with the AssetManager, but I receive a **com.badlogic.gdx.utils.GdxRuntimeException: No loader for type: TiledMap**. Where is this class? 

And your sample code doesn't use any loader for the TiledMap.

**Comment by dsaltares** [comment]
I'm pretty sure Libgdx comes with the TiledMapLoader registered by default. What is the stacktrace? Try manually registering the loader.

http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/assets/AssetManager.html#setLoader-java.lang.Class-com.badlogic.gdx.assets.loaders.AssetLoader-

http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/maps/tiled/TmxMapLoader.html

Maybe that part wasn't clear enough.

**Comment by dsaltares** [comment]
As we do in [this sample](https://github.com/siondream/libgdx-cookbook/blob/master/samples/core/src/com/cookbook/samples/AssetManagerSample.java#L41) you need to.

``` java
AssetManager manager = new AssetManager();
manager.setLoader(TiledMap.class, new TmxMapLoader(new InternalFileHandleResolver()));
```
