### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by tzvetkovg** [siondream/libgdx-cookbook#4]
I've imported the sample project into eclipse and built it successfully. However, when I try to run any project from the main class in the desktop project it always says - file "file name" not found (internal). I've tried gradle--refresh all and cleaning all the projects. None of these helped so I cannot run any of the samples..

**Comment by Shrafe** [comment]
Most likely you'll need to edit the working directory of the particular example you're trying to run. If you want to pastebin your exact error I can help further.

**Comment by dsaltares** [comment]
@Shrafe is correct. You can do that via the properties in the run configuration for the Desktop project. You need to set the working directory to be the data folder within the Android project (use relative paths). The cookbook explains the process in the first recipe.
