### ISSUE TITLE
Wrong release link for 1.3.0

### ISSUE THREAD

**Issue by nicofr69** [siondream/libgdx-cookbook#7]
Hello David
On your main page
https://github.com/saltares/libgdx-cookbook
the link
cookbook-1.3.0 Libgdx 1.6.5, gdx-ai 1.5.0 and Ashley 1.6.0
points to 
https://github.com/saltares/libgdx-cookbook/releases/tag/cookbook-1.2.0
but should point to
https://github.com/saltares/libgdx-cookbook/releases/tag/cookbook-1.3.0
Thanks,
Best regards,
Nikolas

**Comment by dsaltares** [comment]
Thanks for reporting, fixed!
